### ISSUE TITLE
好像用不了了，代码还打算更新吗？

### ISSUE THREAD

**Issue by kongdada** [pengsea/chrome-extensions#1]

**Comment by pengsea** [comment]
我这边是正常可以删除的啊  不知道你是卡在哪一步?

**Comment by kongdada** [comment]
感谢回复，刚才又试了一遍，可以使用。可能是以前误操作吧。
想问问有没有办法分类删除，比如只删除原创的微博。

**Comment by pengsea** [comment]
能举个例子么,给我个具体的微博什么的,我平常很少用微博,不熟悉

**Comment by kongdada** [comment]
![image](https://user-images.githubusercontent.com/19504854/44253958-eabbad00-a233-11e8-9138-bcba9e751c0b.png)
就这个分类，原创的是你自己写的文字啥的，转发别人的内容就不属于原创内容。我删除的时候只打算删掉自己原创的内容，转发别人的微博我不想删掉。

**Comment by pengsea** [comment]
你只要切换到原创界面,就可以直接删除了,不会删除你转发的内容的,
这个工具只会删除你当前页面可以看到的微博
你也可以勾选具体的微博,用接口删除的方式
原创的url里包含这些字段  profile_ftype=1&is_ori=1
