### ISSUE TITLE
接口删除删不掉，慢删除把女盆友删了。

### ISSUE THREAD

**Issue by YSMull** [pengsea/chrome-extensions#2]
建议写好测好了再发布。我只勾选了要删除的僵尸粉，结果把我老同学和女朋友粉都给删没了。

**Comment by pengsea** [comment]
抱歉,删粉丝功能我这边测试是正常的.不知道你具体的操作步骤是什么?
慢删除是 模拟点击事件 当前页面 全部删除 的,和下面的 勾选接口 选中删除 是两种方式

**Comment by 00x16** [comment]
我是选中删除没有用，打开到粉丝页面，全选，开始删除，显示已经删除多少条，然后刷新还在，没删掉

**Comment by pengsea** [comment]
@vincentcqw 是因为微博的接口有变动,代码已经修复了

**Comment by 00x16** [comment]
thanks

发自我的iPhone
